[package]
name = "amalgam-utils"
version.workspace = true
authors.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[features]

[dependencies]
cosmwasm-schema.workspace = true
cosmwasm-std.workspace = true
cw-storage-plus.workspace = true
cw2.workspace = true
prost = "0.14.0"
schemars.workspace = true
serde.workspace = true
thiserror.workspace = true

amalgam-macros = { path = "../amalgam-macros" }
